# Generated by Django 5.0.1 on 2024-02-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
