# Generated by Django 5.0.2 on 2024-02-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('polls', '0013_delete_document'),
        ('users', '0006_alter_myuseer_is_staff_alter_myuseer_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUseer',
            new_name='MyUser',
        ),
    ]
