# Generated by Django 5.0.2 on 2024-02-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('polls', '0013_delete_document'),
        ('users', '0009_rename_phone_number_myuser_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='MyUseer',
        ),
    ]
