# Generated by Django 5.0.1 on 2024-02-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        ('users', '0002_myuseer_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.myuseer'),
        ),
    ]
