# Generated by Django 5.0.1 on 2024-02-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_vote_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shaxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familya', models.CharField(max_length=255)),
                ('ism', models.CharField(max_length=255)),
            ],
        ),
    ]
