# Generated by Django 5.0.1 on 2024-02-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_shaxs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shaxs',
        ),
    ]
