# Generated by Django 5.0.1 on 2024-02-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
