# Generated by Django 5.0.1 on 2024-02-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_dog_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
