# Generated by Django 5.0.1 on 2024-02-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
