# Generated by Django 5.0.2 on 2024-02-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
