# Generated by Django 5.0.2 on 2024-02-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_uploadedfile_rename_dog_video_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
