# Generated by Django 5.0.2 on 2024-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
