# Generated by Django 5.0.2 on 2024-02-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_rename_image_video_video_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_name',
            new_name='name',
        ),
    ]
