# Generated by Django 5.0.2 on 2024-02-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_rename_video_file_video_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(upload_to='vid/'),
        ),
    ]
