# Generated by Django 5.0.2 on 2024-02-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_video_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='name_n',
        ),
    ]
