# Generated by Django 5.0.2 on 2024-02-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_rename_name_video_name_n'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name_n',
            new_name='name',
        ),
    ]
