# Generated by Django 5.0.2 on 2024-02-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_rename_name_n_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(upload_to='videolar/'),
        ),
    ]
