# Generated by Django 5.0.1 on 2024-02-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seting', '0002_rename_familiya_person_familya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('pdf_fayli', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
