# Generated by Django 5.0.1 on 2024-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seting', '0003_kitob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='pdf_fayli',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
