# Generated by Django 5.0.1 on 2024-02-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seting', '0004_alter_kitob_pdf_fayli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitob',
            old_name='pdf_fayli',
            new_name='file',
        ),
    ]
