# Generated by Django 5.0.1 on 2024-02-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seting', '0005_rename_pdf_fayli_kitob_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitob',
            old_name='file',
            new_name='pdf_fayli',
        ),
    ]
