# Generated by Django 5.0.1 on 2024-02-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seting', '0006_rename_file_kitob_pdf_fayli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='kitob',
            name='nomi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='pdf_fayli',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
