# Generated by Django 5.0.1 on 2024-02-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seting', '0008_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
