# Generated by Django 5.0.1 on 2024-02-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seting', '0009_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.DeleteModel(
            name='Kitob',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
